jobs:
- name: development
  plan:
  - get: dataworks-analytical-service-infra
    trigger: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: app
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'dataworks-analytical-service-infra/terraform/deploy/infra'
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'dataworks-analytical-service-infra/terraform/deploy/infra'
