jobs:
- name: integration
  plan:
  - get: dataworks-analytical-service-infra
    trigger: true
    passed:
      - qa
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: infra
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: integration
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: integration

