jobs:
- name: qa
  plan:
  - get: dataworks-analytical-service-infra
    trigger: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: infra
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'dataworks-analytical-service-infra/terraform/deploy/infra'
    params:
      TF_WORKSPACE: qa
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'dataworks-analytical-service-infra/terraform/deploy/infra'
    params:
      TF_WORKSPACE: qa
