jobs:
- name: qa
  plan:
  - get: dataworks-analytical-service-infra
    trigger: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    params:
      DEPLOY_PATH: infra
  - .: (( inject meta.plan.terraform-apply ))
    params:
      TF_WORKSPACE: qa
  - .: (( inject meta.plan.terraform-plan ))
    params:
      TF_WORKSPACE: qa
